/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 3 poll, send_tm_aoi, send_tm_mcp
typedef enum {
   i_send_tm_aoi,
   i_send_tm_mcp
} T_gui_PI_list;

typedef enum {
   i_trig_aoi,
   i_trig_mcp,
   i_trig_pwr
} T_gui_RI_list;

