/* Body file for function HAL
 * Generated by TASTE on 2023-03-17 00:46:27
 */
#include "hal_vm_if.h"




unsigned hal_initialized = 0;
void init_hal(void)
{
   if (0 == hal_initialized) {
      hal_initialized = 1;
      // Call user code startup function
      extern void hal_startup(void);
      hal_startup();
      hal_initialized = 2;
   }
}
void hal_blink_led()
{

   //  Directly call user code, no parameters to pass
   extern void hal_PI_blink_led(void);
   hal_PI_blink_led();
   // puts ("hal_blink_led called");
}

