/* Body file for function tm_collection
 * Generated by TASTE on 2022-11-27 16:30:03
 * You can edit this file, it will not be overwritten
 * Provided interfaces : collect_tm
 * Required interfaces : request_tm
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "tm_collection.h"
//#include <stdio.h>


void tm_collection_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[tm_collection] Startup");
}

void tm_collection_PI_collect_tm(void)
{
   // Write your code here
}


