/* Header file for function tm_collection
 * Generated by TASTE on 2023-03-06 19:54:18
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void tm_collection_startup(void);

/* Provided interfaces */
void tm_collection_PI_collect_tm( void );

/* Required interfaces */
extern void tm_collection_RI_request_tm( asn1SccTemperature_Generic *, asn1SccDeployment_Digital *, asn1SccDeployment_Analogue * );


#ifdef __cplusplus
}
#endif
