/* Header file for function tm_collection
 * Generated by TASTE on 2023-03-17 00:46:27
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void tm_collection_startup(void);

/* Provided interfaces */
void tm_collection_PI_collect_tm( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
