/* Body file for function blinker
 * Generated by TASTE on 2023-03-11 00:05:02
 */
#include "blinker_vm_if.h"




unsigned blinker_initialized = 0;
void init_blinker(void)
{
   if (0 == blinker_initialized) {
      blinker_initialized = 1;
      // Call user code startup function
      extern void blinker_startup(void);
      blinker_startup();
      blinker_initialized = 2;
   }
}
void blinker_blink_trigger()
{

   //  Directly call user code, no parameters to pass
   extern void blinker_PI_blink_trigger(void);
   blinker_PI_blink_trigger();
   // puts ("blinker_blink_trigger called");
}

