#ifndef GENERATED_ASN1SCC_Context_tm_provider_H
#define GENERATED_ASN1SCC_Context_tm_provider_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_tm_provider --------------------------------------------*/
typedef struct {
    asn1SccCounterK k;

} asn1SccContext_tm_provider;

flag asn1SccContext_tm_provider_Equal(const asn1SccContext_tm_provider* pVal1, const asn1SccContext_tm_provider* pVal2);

#define ERR_CONTEXT_TM_PROVIDER		181  /**/
#define ERR_CONTEXT_TM_PROVIDER_K_2		176  /**/
flag asn1SccContext_tm_provider_IsConstraintValid(const asn1SccContext_tm_provider* pVal, int* pErrCode);

void asn1SccContext_tm_provider_Initialize(asn1SccContext_tm_provider* pVal);

#define ERR_UPER_ENCODE_CONTEXT_TM_PROVIDER		182  /**/
#define ERR_UPER_ENCODE_CONTEXT_TM_PROVIDER_K_2		177  /**/
#define asn1SccContext_tm_provider_REQUIRED_BYTES_FOR_ENCODING       2 
#define asn1SccContext_tm_provider_REQUIRED_BITS_FOR_ENCODING        10

flag asn1SccContext_tm_provider_Encode(const asn1SccContext_tm_provider* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_TM_PROVIDER		183  /**/
#define ERR_UPER_DECODE_CONTEXT_TM_PROVIDER_K_2		178  /**/
flag asn1SccContext_tm_provider_Decode(asn1SccContext_tm_provider* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_TM_PROVIDER		184  /**/
#define ERR_ACN_ENCODE_CONTEXT_TM_PROVIDER_K_2		179  /**/
#define asn1SccContext_tm_provider_REQUIRED_BYTES_FOR_ACN_ENCODING       2 
#define asn1SccContext_tm_provider_REQUIRED_BITS_FOR_ACN_ENCODING        10

flag asn1SccContext_tm_provider_ACN_Encode(const asn1SccContext_tm_provider* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_TM_PROVIDER		185  /**/
#define ERR_ACN_DECODE_CONTEXT_TM_PROVIDER_K_2		180  /**/
flag asn1SccContext_tm_provider_ACN_Decode(asn1SccContext_tm_provider* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_tm_provider tm_provider_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
