/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "dataview-uniq.h"




flag asn1SccCounterK_Equal(const asn1SccCounterK* pVal1, const asn1SccCounterK* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccCounterK_IsConstraintValid(const asn1SccCounterK* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 1000UL);
    *pErrCode = ret ? 0 :  ERR_COUNTERK; 

	return ret;
}

void asn1SccCounterK_Initialize(asn1SccCounterK* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccCounterK_Encode(const asn1SccCounterK* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCounterK_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 1000);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccCounterK_Decode(asn1SccCounterK* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 1000);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_COUNTERK;

	return ret  && asn1SccCounterK_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccCounterK_ACN_Encode(const asn1SccCounterK* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCounterK_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 1000);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccCounterK_ACN_Decode(asn1SccCounterK* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 1000);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_COUNTERK;

    return ret && asn1SccCounterK_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccTime_UNIX_Equal(const asn1SccTime_UNIX* pVal1, const asn1SccTime_UNIX* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccTime_UNIX_IsConstraintValid(const asn1SccTime_UNIX* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967294UL);
    *pErrCode = ret ? 0 :  ERR_TIME_UNIX; 

	return ret;
}

void asn1SccTime_UNIX_Initialize(asn1SccTime_UNIX* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccTime_UNIX_Encode(const asn1SccTime_UNIX* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTime_UNIX_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccTime_UNIX_Decode(asn1SccTime_UNIX* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TIME_UNIX;

	return ret  && asn1SccTime_UNIX_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccTime_UNIX_ACN_Encode(const asn1SccTime_UNIX* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTime_UNIX_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccTime_UNIX_ACN_Decode(asn1SccTime_UNIX* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_TIME_UNIX;

    return ret && asn1SccTime_UNIX_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccLatitude_WGS84_Equal(const asn1SccLatitude_WGS84* pVal1, const asn1SccLatitude_WGS84* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccLatitude_WGS84_IsConstraintValid(const asn1SccLatitude_WGS84* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-9.0000000000000000000E+001 <= (*(pVal))) && ((*(pVal)) <= 9.0000000000000000000E+001));
    *pErrCode = ret ? 0 :  ERR_LATITUDE_WGS84; 

	return ret;
}

void asn1SccLatitude_WGS84_Initialize(asn1SccLatitude_WGS84* pVal)
{
	(void)pVal;


	(*(pVal)) = 0.0000000000000000000E+000;
}

flag asn1SccLatitude_WGS84_Encode(const asn1SccLatitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLatitude_WGS84_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLatitude_WGS84_Decode(asn1SccLatitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_LATITUDE_WGS84;

	return ret  && asn1SccLatitude_WGS84_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccLatitude_WGS84_ACN_Encode(const asn1SccLatitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLatitude_WGS84_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLatitude_WGS84_ACN_Decode(asn1SccLatitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_LATITUDE_WGS84;

    return ret && asn1SccLatitude_WGS84_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccLongitude_WGS84_Equal(const asn1SccLongitude_WGS84* pVal1, const asn1SccLongitude_WGS84* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccLongitude_WGS84_IsConstraintValid(const asn1SccLongitude_WGS84* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1.8000000000000000000E+002 <= (*(pVal))) && ((*(pVal)) <= 1.8000000000000000000E+002));
    *pErrCode = ret ? 0 :  ERR_LONGITUDE_WGS84; 

	return ret;
}

void asn1SccLongitude_WGS84_Initialize(asn1SccLongitude_WGS84* pVal)
{
	(void)pVal;


	(*(pVal)) = 0.0000000000000000000E+000;
}

flag asn1SccLongitude_WGS84_Encode(const asn1SccLongitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLongitude_WGS84_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLongitude_WGS84_Decode(asn1SccLongitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_LONGITUDE_WGS84;

	return ret  && asn1SccLongitude_WGS84_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccLongitude_WGS84_ACN_Encode(const asn1SccLongitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLongitude_WGS84_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLongitude_WGS84_ACN_Decode(asn1SccLongitude_WGS84* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_LONGITUDE_WGS84;

    return ret && asn1SccLongitude_WGS84_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccLocation_Equal(const asn1SccLocation* pVal1, const asn1SccLocation* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->lat == pVal2->lat);

    if (ret) {
        ret = (pVal1->lon == pVal2->lon);

    }

	return ret;

}

flag asn1SccLocation_IsConstraintValid(const asn1SccLocation* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccLatitude_WGS84_IsConstraintValid((&(pVal->lat)), pErrCode);
    if (ret) {
        ret = asn1SccLongitude_WGS84_IsConstraintValid((&(pVal->lon)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void asn1SccLocation_Initialize(asn1SccLocation* pVal)
{
	(void)pVal;



	/*set lat */
	asn1SccLatitude_WGS84_Initialize((&(pVal->lat)));
	/*set lon */
	asn1SccLongitude_WGS84_Initialize((&(pVal->lon)));
}

flag asn1SccLocation_Encode(const asn1SccLocation* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLocation_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode lat */
	    ret = asn1SccLatitude_WGS84_Encode((&(pVal->lat)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode lon */
	        ret = asn1SccLongitude_WGS84_Encode((&(pVal->lon)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLocation_Decode(asn1SccLocation* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode lat */
	ret = asn1SccLatitude_WGS84_Decode((&(pVal->lat)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode lon */
	    ret = asn1SccLongitude_WGS84_Decode((&(pVal->lon)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccLocation_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccLocation_ACN_Encode(const asn1SccLocation* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLocation_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode lat */
	    ret = asn1SccLatitude_WGS84_ACN_Encode((&(pVal->lat)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode lon */
	        ret = asn1SccLongitude_WGS84_ACN_Encode((&(pVal->lon)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLocation_ACN_Decode(asn1SccLocation* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode lat */
	ret = asn1SccLatitude_WGS84_ACN_Decode((&(pVal->lat)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode lon */
	    ret = asn1SccLongitude_WGS84_ACN_Decode((&(pVal->lon)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccLocation_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccLocation_Fix_Packet_Equal(const asn1SccLocation_Fix_Packet* pVal1, const asn1SccLocation_Fix_Packet* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->t == pVal2->t);

    if (ret) {
        ret = (pVal1->lat == pVal2->lat);

        if (ret) {
            ret = (pVal1->lon == pVal2->lon);

        }

    }

	return ret;

}

flag asn1SccLocation_Fix_Packet_IsConstraintValid(const asn1SccLocation_Fix_Packet* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccTime_UNIX_IsConstraintValid((&(pVal->t)), pErrCode);
    if (ret) {
        ret = asn1SccLatitude_WGS84_IsConstraintValid((&(pVal->lat)), pErrCode);
        if (ret) {
            ret = asn1SccLongitude_WGS84_IsConstraintValid((&(pVal->lon)), pErrCode);
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void asn1SccLocation_Fix_Packet_Initialize(asn1SccLocation_Fix_Packet* pVal)
{
	(void)pVal;



	/*set t */
	asn1SccTime_UNIX_Initialize((&(pVal->t)));
	/*set lat */
	asn1SccLatitude_WGS84_Initialize((&(pVal->lat)));
	/*set lon */
	asn1SccLongitude_WGS84_Initialize((&(pVal->lon)));
}

flag asn1SccLocation_Fix_Packet_Encode(const asn1SccLocation_Fix_Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLocation_Fix_Packet_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode t */
	    ret = asn1SccTime_UNIX_Encode((&(pVal->t)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode lat */
	        ret = asn1SccLatitude_WGS84_Encode((&(pVal->lat)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode lon */
	            ret = asn1SccLongitude_WGS84_Encode((&(pVal->lon)), pBitStrm, pErrCode, FALSE);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLocation_Fix_Packet_Decode(asn1SccLocation_Fix_Packet* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode t */
	ret = asn1SccTime_UNIX_Decode((&(pVal->t)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode lat */
	    ret = asn1SccLatitude_WGS84_Decode((&(pVal->lat)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode lon */
	        ret = asn1SccLongitude_WGS84_Decode((&(pVal->lon)), pBitStrm, pErrCode);
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccLocation_Fix_Packet_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccLocation_Fix_Packet_ACN_Encode(const asn1SccLocation_Fix_Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLocation_Fix_Packet_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode t */
	    ret = asn1SccTime_UNIX_ACN_Encode((&(pVal->t)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode lat */
	        ret = asn1SccLatitude_WGS84_ACN_Encode((&(pVal->lat)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode lon */
	            ret = asn1SccLongitude_WGS84_ACN_Encode((&(pVal->lon)), pBitStrm, pErrCode, FALSE);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccLocation_Fix_Packet_ACN_Decode(asn1SccLocation_Fix_Packet* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode t */
	ret = asn1SccTime_UNIX_ACN_Decode((&(pVal->t)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode lat */
	    ret = asn1SccLatitude_WGS84_ACN_Decode((&(pVal->lat)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode lon */
	        ret = asn1SccLongitude_WGS84_ACN_Decode((&(pVal->lon)), pBitStrm, pErrCode);
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccLocation_Fix_Packet_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccTemperature_Generic_Equal(const asn1SccTemperature_Generic* pVal1, const asn1SccTemperature_Generic* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccTemperature_Generic_IsConstraintValid(const asn1SccTemperature_Generic* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2.0000000000000000000E+002 <= (*(pVal))) && ((*(pVal)) <= 2.0000000000000000000E+002));
    *pErrCode = ret ? 0 :  ERR_TEMPERATURE_GENERIC; 

	return ret;
}

void asn1SccTemperature_Generic_Initialize(asn1SccTemperature_Generic* pVal)
{
	(void)pVal;


	(*(pVal)) = 0.0000000000000000000E+000;
}

flag asn1SccTemperature_Generic_Encode(const asn1SccTemperature_Generic* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTemperature_Generic_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccTemperature_Generic_Decode(asn1SccTemperature_Generic* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURE_GENERIC;

	return ret  && asn1SccTemperature_Generic_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccTemperature_Generic_ACN_Encode(const asn1SccTemperature_Generic* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTemperature_Generic_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccTemperature_Generic_ACN_Decode(asn1SccTemperature_Generic* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_TEMPERATURE_GENERIC;

    return ret && asn1SccTemperature_Generic_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccDeployment_Digital_Equal(const asn1SccDeployment_Digital* pVal1, const asn1SccDeployment_Digital* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccDeployment_Digital_IsConstraintValid(const asn1SccDeployment_Digital* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void asn1SccDeployment_Digital_Initialize(asn1SccDeployment_Digital* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}

flag asn1SccDeployment_Digital_Encode(const asn1SccDeployment_Digital* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccDeployment_Digital_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccDeployment_Digital_Decode(asn1SccDeployment_Digital* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_DEPLOYMENT_DIGITAL;

	return ret  && asn1SccDeployment_Digital_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccDeployment_Digital_ACN_Encode(const asn1SccDeployment_Digital* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccDeployment_Digital_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccDeployment_Digital_ACN_Decode(asn1SccDeployment_Digital* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_DEPLOYMENT_DIGITAL;

    return ret && asn1SccDeployment_Digital_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccDeployment_Analogue_Equal(const asn1SccDeployment_Analogue* pVal1, const asn1SccDeployment_Analogue* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccDeployment_Analogue_IsConstraintValid(const asn1SccDeployment_Analogue* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((0.0000000000000000000E+000 <= (*(pVal))) && ((*(pVal)) <= 1.0000000000000000000E+002));
    *pErrCode = ret ? 0 :  ERR_DEPLOYMENT_ANALOGUE; 

	return ret;
}

void asn1SccDeployment_Analogue_Initialize(asn1SccDeployment_Analogue* pVal)
{
	(void)pVal;


	(*(pVal)) = 0.0000000000000000000E+000;
}

flag asn1SccDeployment_Analogue_Encode(const asn1SccDeployment_Analogue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccDeployment_Analogue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccDeployment_Analogue_Decode(asn1SccDeployment_Analogue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_DEPLOYMENT_ANALOGUE;

	return ret  && asn1SccDeployment_Analogue_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccDeployment_Analogue_ACN_Encode(const asn1SccDeployment_Analogue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccDeployment_Analogue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccDeployment_Analogue_ACN_Decode(asn1SccDeployment_Analogue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_DEPLOYMENT_ANALOGUE;

    return ret && asn1SccDeployment_Analogue_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccSystem_Mode_Equal(const asn1SccSystem_Mode* pVal1, const asn1SccSystem_Mode* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccSystem_Mode_IsConstraintValid(const asn1SccSystem_Mode* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4UL);
    *pErrCode = ret ? 0 :  ERR_SYSTEM_MODE; 

	return ret;
}

void asn1SccSystem_Mode_Initialize(asn1SccSystem_Mode* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccSystem_Mode_Encode(const asn1SccSystem_Mode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSystem_Mode_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccSystem_Mode_Decode(asn1SccSystem_Mode* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_SYSTEM_MODE;

	return ret  && asn1SccSystem_Mode_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccSystem_Mode_ACN_Encode(const asn1SccSystem_Mode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSystem_Mode_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccSystem_Mode_ACN_Decode(asn1SccSystem_Mode* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_SYSTEM_MODE;

    return ret && asn1SccSystem_Mode_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccSubsystem_Address_Equal(const asn1SccSubsystem_Address* pVal1, const asn1SccSubsystem_Address* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccSubsystem_Address_IsConstraintValid(const asn1SccSubsystem_Address* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 6UL);
    *pErrCode = ret ? 0 :  ERR_SUBSYSTEM_ADDRESS; 

	return ret;
}

void asn1SccSubsystem_Address_Initialize(asn1SccSubsystem_Address* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccSubsystem_Address_Encode(const asn1SccSubsystem_Address* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSubsystem_Address_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 6);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccSubsystem_Address_Decode(asn1SccSubsystem_Address* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 6);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_SUBSYSTEM_ADDRESS;

	return ret  && asn1SccSubsystem_Address_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccSubsystem_Address_ACN_Encode(const asn1SccSubsystem_Address* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSubsystem_Address_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 6);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccSubsystem_Address_ACN_Decode(asn1SccSubsystem_Address* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 6);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_SUBSYSTEM_ADDRESS;

    return ret && asn1SccSubsystem_Address_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccMode_Change_Packet_ttl_ms_Equal(const asn1SccMode_Change_Packet_ttl_ms* pVal1, const asn1SccMode_Change_Packet_ttl_ms* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccMode_Change_Packet_Equal(const asn1SccMode_Change_Packet* pVal1, const asn1SccMode_Change_Packet* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->target_addr == pVal2->target_addr);

    if (ret) {
        ret = (pVal1->target_mode == pVal2->target_mode);

        if (ret) {
            ret = asn1SccMode_Change_Packet_ttl_ms_Equal((&(pVal1->ttl_ms)), (&(pVal2->ttl_ms)));

        }

    }

	return ret;

}

flag asn1SccMode_Change_Packet_ttl_ms_IsConstraintValid(const asn1SccMode_Change_Packet_ttl_ms* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 10000UL);
    *pErrCode = ret ? 0 :  ERR_MODE_CHANGE_PACKET_TTL_MS; 

	return ret;
}

flag asn1SccMode_Change_Packet_IsConstraintValid(const asn1SccMode_Change_Packet* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccSubsystem_Address_IsConstraintValid((&(pVal->target_addr)), pErrCode);
    if (ret) {
        ret = asn1SccSystem_Mode_IsConstraintValid((&(pVal->target_mode)), pErrCode);
        if (ret) {
            ret = asn1SccMode_Change_Packet_ttl_ms_IsConstraintValid((&(pVal->ttl_ms)), pErrCode);
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void asn1SccMode_Change_Packet_ttl_ms_Initialize(asn1SccMode_Change_Packet_ttl_ms* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}
void asn1SccMode_Change_Packet_Initialize(asn1SccMode_Change_Packet* pVal)
{
	(void)pVal;



	/*set target_addr */
	asn1SccSubsystem_Address_Initialize((&(pVal->target_addr)));
	/*set target_mode */
	asn1SccSystem_Mode_Initialize((&(pVal->target_mode)));
	/*set ttl_ms */
	asn1SccMode_Change_Packet_ttl_ms_Initialize((&(pVal->ttl_ms)));
}

flag asn1SccMode_Change_Packet_Encode(const asn1SccMode_Change_Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccMode_Change_Packet_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode target_addr */
	    ret = asn1SccSubsystem_Address_Encode((&(pVal->target_addr)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode target_mode */
	        ret = asn1SccSystem_Mode_Encode((&(pVal->target_mode)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode ttl_ms */
	            BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->ttl_ms, 0, 10000);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccMode_Change_Packet_Decode(asn1SccMode_Change_Packet* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode target_addr */
	ret = asn1SccSubsystem_Address_Decode((&(pVal->target_addr)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode target_mode */
	    ret = asn1SccSystem_Mode_Decode((&(pVal->target_mode)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode ttl_ms */
	        ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->ttl_ms)), 0, 10000);
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_MODE_CHANGE_PACKET_TTL_MS;
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccMode_Change_Packet_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccMode_Change_Packet_ACN_Encode(const asn1SccMode_Change_Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccMode_Change_Packet_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode target_addr */
	    ret = asn1SccSubsystem_Address_ACN_Encode((&(pVal->target_addr)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode target_mode */
	        ret = asn1SccSystem_Mode_ACN_Encode((&(pVal->target_mode)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode ttl_ms */
	            BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->ttl_ms, 0, 10000);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccMode_Change_Packet_ACN_Decode(asn1SccMode_Change_Packet* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode target_addr */
	ret = asn1SccSubsystem_Address_ACN_Decode((&(pVal->target_addr)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode target_mode */
	    ret = asn1SccSystem_Mode_ACN_Decode((&(pVal->target_mode)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode ttl_ms */
	        ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->ttl_ms)), 0, 10000);
	        *pErrCode = ret ? 0 : ERR_ACN_DECODE_MODE_CHANGE_PACKET_TTL_MS;
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccMode_Change_Packet_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648L <= (*(pVal))) && ((*(pVal)) <= 2147483647L));
    *pErrCode = ret ? 0 :  ERR_T_INT32; 

	return ret;
}

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT32;

	return ret  && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT32;

    return ret && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT32; 

	return ret;
}

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT32;

	return ret  && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT32;

    return ret && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-128L <= (*(pVal))) && ((*(pVal)) <= 127L));
    *pErrCode = ret ? 0 :  ERR_T_INT8; 

	return ret;
}

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT8;

	return ret  && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT8;

    return ret && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT8; 

	return ret;
}

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT8;

	return ret  && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT8;

    return ret && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_BOOLEAN;

	return ret  && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_BOOLEAN;

    return ret && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal)
{
	(void)pVal;


}

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;



	return ret  && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}



flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((((((*(pVal)) == PID_gui)) || (((*(pVal)) == PID_loc_provider)))) || (((*(pVal)) == PID_state_handler_entrypoint)))) || (((*(pVal)) == PID_tc_provider)))) || (((*(pVal)) == PID_tc_validation)))) || (((*(pVal)) == PID_tm_collection)))) || (((*(pVal)) == PID_tm_provider)))) || (((*(pVal)) == PID_env)));
    *pErrCode = ret ? 0 :  ERR_PID; 

	return ret;
}

void asn1SccPID_Initialize(asn1SccPID* pVal)
{
	(void)pVal;


	(*(pVal)) = PID_gui;
}

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) 
	    {
	        case PID_gui:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 7);
	        	break;
	        case PID_loc_provider:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 7);
	        	break;
	        case PID_state_handler_entrypoint:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 7);
	        	break;
	        case PID_tc_provider:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 7);
	        	break;
	        case PID_tc_validation:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 7);
	        	break;
	        case PID_tm_collection:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 5, 0, 7);
	        	break;
	        case PID_tm_provider:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 6, 0, 7);
	        	break;
	        case PID_env:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 7, 0, 7);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_PID; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 7);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_PID;
	    if (ret) {
	        switch(enumIndex) 
	        {
	            case 0: 
	                (*(pVal)) = PID_gui;
	                break;
	            case 1: 
	                (*(pVal)) = PID_loc_provider;
	                break;
	            case 2: 
	                (*(pVal)) = PID_state_handler_entrypoint;
	                break;
	            case 3: 
	                (*(pVal)) = PID_tc_provider;
	                break;
	            case 4: 
	                (*(pVal)) = PID_tc_validation;
	                break;
	            case 5: 
	                (*(pVal)) = PID_tm_collection;
	                break;
	            case 6: 
	                (*(pVal)) = PID_tm_provider;
	                break;
	            case 7: 
	                (*(pVal)) = PID_env;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_PID;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = PID_gui;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) { 
	        case PID_gui:
	            intVal = 0;
	            break;
	        case PID_loc_provider:
	            intVal = 1;
	            break;
	        case PID_state_handler_entrypoint:
	            intVal = 2;
	            break;
	        case PID_tc_provider:
	            intVal = 3;
	            break;
	        case PID_tc_validation:
	            intVal = 4;
	            break;
	        case PID_tm_collection:
	            intVal = 5;
	            break;
	        case PID_tm_provider:
	            intVal = 6;
	            break;
	        case PID_env:
	            intVal = 7;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 7);
	    }
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal)), 0, 7);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID;
	if (ret) {
	    switch (intVal) {
	        case 0:
	            (*(pVal)) = PID_gui;
	            break;
	        case 1:
	            (*(pVal)) = PID_loc_provider;
	            break;
	        case 2:
	            (*(pVal)) = PID_state_handler_entrypoint;
	            break;
	        case 3:
	            (*(pVal)) = PID_tc_provider;
	            break;
	        case 4:
	            (*(pVal)) = PID_tc_validation;
	            break;
	        case 5:
	            (*(pVal)) = PID_tm_collection;
	            break;
	        case 6:
	            (*(pVal)) = PID_tm_provider;
	            break;
	        case 7:
	            (*(pVal)) = PID_env;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}

