/* Body file for function led_blinker
 * Generated by TASTE on 2023-03-10 23:38:53
 */
#include "led_blinker_vm_if.h"




unsigned led_blinker_initialized = 0;
void init_led_blinker(void)
{
   if (0 == led_blinker_initialized) {
      led_blinker_initialized = 1;
      // Call user code startup function
      extern void led_blinker_startup(void);
      led_blinker_startup();
      led_blinker_initialized = 2;
   }
}
void led_blinker_trigger_blink()
{

   //  Directly call user code, no parameters to pass
   extern void led_blinker_PI_trigger_blink(void);
   led_blinker_PI_trigger_blink();
   // puts ("led_blinker_trigger_blink called");
}

