/* Header file for function HAL
 * Generated by TASTE on 2023-03-30 18:41:54
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void hal_startup(void);

/* Provided interfaces */
void hal_PI_blink_led( void );


void hal_PI_get_altitude( asn1SccAltitude_m * );


void hal_PI_get_gps( asn1SccLatitude_WGS84 *, asn1SccLongitude_WGS84 * );


void hal_PI_set_led( const asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
