/* Header file for function HAL
 * Generated by TASTE on 2023-04-02 23:30:02
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void hal_startup(void);

/* Provided interfaces */
void hal_PI_blink_led( void );


void hal_PI_set_led( const asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
