/* Body file for function HAL
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "hal.h"
//#include <stdio.h>


void hal_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[HAL] Startup");
}

void hal_PI_blink_led(void)
{
   // Write your code here
}


void hal_PI_set_led
      (const asn1SccT_Boolean *IN_val)

{
   // Write your code here
}


