/* ASN.1 System configuration file for function HAL
 * Generated by TASTE on 2023-02-18 14:36:43
 */
#define __NEED_TEMPERATURE_NATIVE


#define __NEED_VOLTAGE_NATIVE


#define __NEED_UINT8T_NATIVE
#define __NEED_T_Boolean_NATIVE


#define __NEED_T_Boolean_NATIVE
#define __NEED_T_Boolean_NATIVE


#define __NEED_T_Boolean_NATIVE
#define __NEED_T_Boolean_NATIVE


#define __NEED_DUTY_CYCLE_NATIVE

