/* Body file for function HAL
 * Generated by TASTE on 2023-02-18 14:36:43
 */
#include "hal_vm_if.h"
#include "C_ASN1_Types.h"




unsigned hal_initialized = 0;
void init_hal(void)
{
   if (0 == hal_initialized) {
      hal_initialized = 1;
      // Call user code startup function
      extern void hal_startup(void);
      hal_startup();
      hal_initialized = 2;
   }
}
void hal_get_current_temperature
      (char *OUT_temperature_value, size_t *OUT_temperature_value_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_get_current_temperature
      (asn1SccTEMPERATURE *);





   // Call user code
   hal_PI_get_current_temperature ((asn1SccTEMPERATURE *)OUT_temperature_value);

}




void hal_get_current_voltage
      (char *OUT_current_voltage, size_t *OUT_current_voltage_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_get_current_voltage
      (asn1SccVOLTAGE *);





   // Call user code
   hal_PI_get_current_voltage ((asn1SccVOLTAGE *)OUT_current_voltage);

}




void hal_oled_load_register
      (const char *IN_register_value, size_t IN_register_value_len,
       char *OUT_success, size_t *OUT_success_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_oled_load_register
      (const asn1SccUINT8T *,
       asn1SccT_Boolean *);





   // Call user code
   hal_PI_oled_load_register ((asn1SccUINT8T *)IN_register_value, (asn1SccT_Boolean *)OUT_success);

}




void hal_oled_set_data_enable
      (const char *IN_enabled, size_t IN_enabled_len,
       char *OUT_success, size_t *OUT_success_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_oled_set_data_enable
      (const asn1SccT_Boolean *,
       asn1SccT_Boolean *);





   // Call user code
   hal_PI_oled_set_data_enable ((asn1SccT_Boolean *)IN_enabled, (asn1SccT_Boolean *)OUT_success);

}




void hal_oled_turn_on_off
      (const char *IN_enabled, size_t IN_enabled_len,
       char *OUT_success, size_t *OUT_success_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_oled_turn_on_off
      (const asn1SccT_Boolean *,
       asn1SccT_Boolean *);





   // Call user code
   hal_PI_oled_turn_on_off ((asn1SccT_Boolean *)IN_enabled, (asn1SccT_Boolean *)OUT_success);

}




void hal_set_pwm
      (const char *IN_pwm_value, size_t IN_pwm_value_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hal_PI_set_pwm
      (const asn1SccDUTY_CYCLE *);





   // Call user code
   hal_PI_set_pwm ((asn1SccDUTY_CYCLE *)IN_pwm_value);

}

