/* Body file for function HAL
 * Generated by TASTE on 2023-03-10 23:20:06
 * You can edit this file, it will not be overwritten
 * Provided interfaces : get_temperature, led_blink
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "hal.h"

#include <msp430.h>
#include <FreeRTOS.h>
#include <semphr.h>

volatile bool P4_6_LED_ON = false;

void hal_startup( void )
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    WDTCTL = WDTPW | WDTHOLD;           // stop watchdog timer
    PM5CTL0 &= ~LOCKLPM5;               // disable the GPIO power-on default high-impedance mode
                                        // to activate previously configured port settings

    P1DIR |= 0x01;                      // Set P1.0 to output direction
    P4DIR |= 0x40;                      // Set P4.6 to output direction
    P4OUT &= ~0x40;                     // Unset P4.6

    __enable_interrupt();               // enable all interrupts
}

void hal_PI_blink_led(void)
{
   // Write your code here
    P1OUT ^= 0x01;                      // Toggle P1.0 using XOR
}

void hal_PI_set_led( const asn1SccT_Boolean *IN_val )
{
    if (*IN_val)
    {
        P4OUT |= 0x40;                  // Set P4.6 using OR
    }
    else
    {
        P4OUT &= ~0x40;                 // Unset P4.6 using AND
    }
    P4_6_LED_ON = *IN_val;
}
