/* Header file for function HAL
 * Generated by TASTE on 2023-03-20 01:12:13
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void hal_startup(void);

/* Provided interfaces */
void hal_PI_blink_led( void );


void hal_PI_read_led( asn1SccT_Boolean * );


void hal_PI_set_led( const asn1SccT_Boolean * );


void hal_PI_toggle_led( const asn1SccDelay_ns * );

/* Required interfaces */
extern void hal_RI_onboard_toggle_led( void );


#ifdef __cplusplus
}
#endif
