/* Body file for function loc_provider
 * Generated by TASTE on 2023-03-17 00:46:27
 */
#include "loc_provider_vm_if.h"
#include "C_ASN1_Types.h"




unsigned loc_provider_initialized = 0;
void init_loc_provider(void)
{
   if (0 == loc_provider_initialized) {
      loc_provider_initialized = 1;
      // Call user code startup function
      extern void loc_provider_startup(void);
      loc_provider_startup();
      loc_provider_initialized = 2;
   }
}
void loc_provider_request_loc
      (char *OUT_lfp, size_t *OUT_lfp_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void loc_provider_PI_request_loc
      (asn1SccLocation_Fix_Packet *);





   // Call user code
   loc_provider_PI_request_loc ((asn1SccLocation_Fix_Packet *)OUT_lfp);

}

