/* Header file for function loc_provider
 * Generated by TASTE on 2023-03-17 00:46:27
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "loc_provider.h"

// Function initialization - calls user startup code of all dependent functions
void init_loc_provider(void);


/* Provided interfaces */
void loc_provider_request_loc
      (char *OUT_lfp, size_t *OUT_lfp_len);


#ifdef __cplusplus
}
#endif

