/* Body file for function loc_provider
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "loc_provider_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned loc_provider_initialized = 0;
void init_loc_provider(void)
{
   if (0 == loc_provider_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      loc_provider_initialized = 1;
      // Call user code startup function
      extern void loc_provider_startup(void);
      loc_provider_startup();
      puts ("[TASTE] Initialization completed for function loc_provider");
      loc_provider_initialized = 2;
   }
}
void loc_provider_request_loc
      (char *OUT_lfp, size_t *OUT_lfp_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: loc_provider,request_loc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void loc_provider_PI_request_loc
      (asn1SccLocation_Fix_Packet *);





   // Call user code
   loc_provider_PI_request_loc ((asn1SccLocation_Fix_Packet *)OUT_lfp);

}

