-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-12-28 10:47:30
package body State_Handler_Entrypoint_RI is

   procedure Collect_Tm is
      procedure C_Collect_Tm
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_collect_tm";
   begin
         C_Collect_Tm;
   end Collect_Tm;
   
   
   
   procedure Request_Loc
      (Lfp : out asn1SccLocation_Fix_Packet) is
      procedure C_Request_Loc
         (Lfp : out asn1SccLocation_Fix_Packet)
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_request_loc";
   begin
         C_Request_Loc (lfp);
   end Request_Loc;
   
   
   
   procedure Request_Tc
      (Mcp : out asn1SccMode_Change_Packet) is
      procedure C_Request_Tc
         (Mcp : out asn1SccMode_Change_Packet)
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_request_tc";
   begin
         C_Request_Tc (mcp);
   end Request_Tc;
   
   
   
   procedure Send_Tm_Aoi
      (Lfp : in out asn1SccLocation_Fix_Packet) is
      procedure C_Send_Tm_Aoi
         (Lfp : in out asn1SccLocation_Fix_Packet)
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_send_tm_aoi";
   begin
         C_Send_Tm_Aoi (lfp);
   end Send_Tm_Aoi;
   
   
   
   procedure Send_Tm_Mcp
      (Mcp : in out asn1SccMode_Change_Packet) is
      procedure C_Send_Tm_Mcp
         (Mcp : in out asn1SccMode_Change_Packet)
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_send_tm_mcp";
   begin
         C_Send_Tm_Mcp (mcp);
   end Send_Tm_Mcp;
   
   
   
   procedure Validate_Mc_Vs_Tm is
      procedure C_Validate_Mc_Vs_Tm
         with Import,
              Convention => C,
              Link_Name  => "state_handler_entrypoint_RI_validate_mc_vs_tm";
   begin
         C_Validate_Mc_Vs_Tm;
   end Validate_Mc_Vs_Tm;

end State_Handler_Entrypoint_RI;
