/* Body file for function tm_provider
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "tm_provider_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned tm_provider_initialized = 0;
void init_tm_provider(void)
{
   if (0 == tm_provider_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      tm_provider_initialized = 1;
      // Call user code startup function
      extern void tm_provider_startup(void);
      tm_provider_startup();
      puts ("[TASTE] Initialization completed for function tm_provider");
      tm_provider_initialized = 2;
   }
}
void tm_provider_request_tm
      (char *OUT_temp, size_t *OUT_temp_len,
       char *OUT_depl_d, size_t *OUT_depl_d_len,
       char *OUT_depl_a, size_t *OUT_depl_a_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tm_provider,request_tm,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void tm_provider_PI_request_tm
      (asn1SccTemperature_Generic *,
       asn1SccDeployment_Digital *,
       asn1SccDeployment_Analogue *);





   // Call user code
   tm_provider_PI_request_tm ((asn1SccTemperature_Generic *)OUT_temp, (asn1SccDeployment_Digital *)OUT_depl_d, (asn1SccDeployment_Analogue *)OUT_depl_a);

}

