/* Header file for function PWM_driver
 * Generated by TASTE on 2023-02-28 19:17:07
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void pwm_driver_startup(void);

/* Provided interfaces */
void pwm_driver_PI_pwm_capture( );


void pwm_driver_PI_pwm_files( );


void pwm_driver_PI_pwm_idle( );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

