/* Body file for function state_handler_entrypoint
 * Generated by TASTE on 2023-03-17 00:46:27
 */
#include "state_handler_entrypoint_vm_if.h"



extern void CInitState_Handler_Entrypoint(void);

extern void init_tm_collection(void);
extern unsigned tm_collection_initialized;
extern void init_loc_provider(void);
extern unsigned loc_provider_initialized;
extern void init_tc_provider(void);
extern unsigned tc_provider_initialized;
unsigned state_handler_entrypoint_initialized = 0;
void init_state_handler_entrypoint(void)
{
   if (0 == state_handler_entrypoint_initialized) {
      state_handler_entrypoint_initialized = 1;
      // Initialize C to call elaboration functions
      CInitState_Handler_Entrypoint();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == tm_collection_initialized) {
          init_tm_collection();
      }
      if (0 == loc_provider_initialized) {
          init_loc_provider();
      }
      if (0 == tc_provider_initialized) {
          init_tc_provider();
      }
      state_handler_entrypoint_initialized = 2;
   }
}
void state_handler_entrypoint_poll_aoi()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_poll_aoi(void);
   state_handler_entrypoint_PI_poll_aoi();
   // puts ("state_handler_entrypoint_poll_aoi called");
}




void state_handler_entrypoint_poll_mcp()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_poll_mcp(void);
   state_handler_entrypoint_PI_poll_mcp();
   // puts ("state_handler_entrypoint_poll_mcp called");
}




void state_handler_entrypoint_toggle_pwr()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_toggle_pwr(void);
   state_handler_entrypoint_PI_toggle_pwr();
   // puts ("state_handler_entrypoint_toggle_pwr called");
}




void state_handler_entrypoint_trig_aoi()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_aoi(void);
   state_handler_entrypoint_PI_trig_aoi();
   // puts ("state_handler_entrypoint_trig_aoi called");
}




void state_handler_entrypoint_trig_mcp()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_mcp(void);
   state_handler_entrypoint_PI_trig_mcp();
   // puts ("state_handler_entrypoint_trig_mcp called");
}




void state_handler_entrypoint_trig_pwr()
{

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_pwr(void);
   state_handler_entrypoint_PI_trig_pwr();
   // puts ("state_handler_entrypoint_trig_pwr called");
}

