/* ASN.1 System configuration file for function state_handler_entrypoint
 * Generated by TASTE on 2023-03-06 19:54:19
 */

#define __NEED_Location_Fix_Packet_NATIVE


#define __NEED_Mode_Change_Packet_NATIVE


#define __NEED_Location_Fix_Packet_NATIVE


#define __NEED_Mode_Change_Packet_NATIVE
