/* Body file for function Payload_subsystem
 * Generated by TASTE on 2023-02-28 19:13:43
 */
#include "payload_subsystem_vm_if.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);



extern void adainit(void);

unsigned payload_subsystem_initialized = 0;
void init_payload_subsystem(void)
{
   if (0 == payload_subsystem_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      payload_subsystem_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      puts ("[TASTE] Initialization completed for function Payload_subsystem");
      payload_subsystem_initialized = 2;
   }
}
void payload_subsystem_Trigger_capture()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: payload_subsystem,trigger_capture,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void payload_subsystem_PI_Trigger_capture(void);
   payload_subsystem_PI_Trigger_capture();
   // puts ("payload_subsystem_trigger_capture called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *payload_subsystem_state(void);
      printf ("INNER_SDL_STATE: payload_subsystem,%s\n", payload_subsystem_state());
      fflush(stdout);
   }
}

