/* Body file for function tc_provider
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "tc_provider_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned tc_provider_initialized = 0;
void init_tc_provider(void)
{
   if (0 == tc_provider_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      tc_provider_initialized = 1;
      // Call user code startup function
      extern void tc_provider_startup(void);
      tc_provider_startup();
      puts ("[TASTE] Initialization completed for function tc_provider");
      tc_provider_initialized = 2;
   }
}
void tc_provider_request_tc
      (char *OUT_mcp, size_t *OUT_mcp_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tc_provider,request_tc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void tc_provider_PI_request_tc
      (asn1SccMode_Change_Packet *);





   // Call user code
   tc_provider_PI_request_tc ((asn1SccMode_Change_Packet *)OUT_mcp);

}

