/* Body file for function tc_provider
 * Generated by TASTE on 2023-03-17 00:46:27
 */
#include "tc_provider_vm_if.h"
#include "C_ASN1_Types.h"




unsigned tc_provider_initialized = 0;
void init_tc_provider(void)
{
   if (0 == tc_provider_initialized) {
      tc_provider_initialized = 1;
      // Call user code startup function
      extern void tc_provider_startup(void);
      tc_provider_startup();
      tc_provider_initialized = 2;
   }
}
void tc_provider_request_tc
      (char *OUT_mcp, size_t *OUT_mcp_len)

{

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void tc_provider_PI_request_tc
      (asn1SccMode_Change_Packet *);





   // Call user code
   tc_provider_PI_request_tc ((asn1SccMode_Change_Packet *)OUT_mcp);

}

