/* Body file for function blinker
 * Generated by TASTE on 2023-03-11 00:01:20
 * You can edit this file, it will not be overwritten
 * Provided interfaces : blink_trigger
 * Required interfaces : toggle_led
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "blinker.h"
//#include <stdio.h>


void blinker_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[blinker] Startup");
}

void blinker_PI_blink_trigger(void)
{
   // Write your code here
    blinker_RI_toggle_led();
}


