/* Body file for function print_service
 * Generated by TASTE on 2023-03-18 10:03:17
 * You can edit this file, it will not be overwritten
 * Provided interfaces : print
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "print_service.h"

#include <msp430.h>
#include <FreeRTOS.h>
#include <semphr.h>

#include "msp430_uart.h"

#include <string.h>

#define NO_LINETERM 0
#define CRLF 1

void print_service_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    WDTCTL = WDTPW | WDTHOLD;               // Stop watchdog timer
    PM5CTL0 &= ~LOCKLPM5;                   // Disable the GPIO power-on default high-impedance mode
                                            // to activate previously configured port settings

    USART0_Init();
    const unsigned char* startup = "[print_service] Startup";
    USART0_SendData(startup, strlen(startup), CRLF);
}

void print_service_PI_wait( void )
{
    const unsigned char* wait = ".";
    USART0_SendData(wait, strlen(wait), NO_LINETERM);
}

void print_service_PI_print( const asn1SccOString* IN_str )
{
    USART0_SendData(IN_str->arr, IN_str->nCount, CRLF);
}

