/* Header file for function HAL
 * Generated by TASTE on 2023-03-17 00:46:27
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void hal_startup(void);

/* Provided interfaces */
void hal_PI_blink_led( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
