pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");
with OBC_MODEL_DATAVIEW; use OBC_MODEL_DATAVIEW;
pragma Warnings (On, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");



package GUI_SUBTYPE with SPARK_Mode
is


subtype asn1SccGui_send_tm_aoi_lfp is OBC_MODEL_DATAVIEW.asn1SccLocation_Fix_Packet;


    function asn1SccGui_send_tm_aoi_lfp_Equal (val1, val2 : asn1SccGui_send_tm_aoi_lfp) return Boolean;

ERR_GUI_SEND_TM_AOI_LFP_2:constant Integer := 206; -- 
function asn1SccGui_send_tm_aoi_lfp_IsConstraintValid(val : asn1SccGui_send_tm_aoi_lfp) return adaasn1rtl.ASN1_RESULT;

function asn1SccGui_send_tm_aoi_lfp_Init return asn1SccGui_send_tm_aoi_lfp;
subtype asn1SccGui_send_tm_mcp_mcp is OBC_MODEL_DATAVIEW.asn1SccMode_Change_Packet;


    function asn1SccGui_send_tm_mcp_mcp_Equal (val1, val2 : asn1SccGui_send_tm_mcp_mcp) return Boolean;

ERR_GUI_SEND_TM_MCP_MCP_2:constant Integer := 241; -- 
function asn1SccGui_send_tm_mcp_mcp_IsConstraintValid(val : asn1SccGui_send_tm_mcp_mcp) return adaasn1rtl.ASN1_RESULT;

function asn1SccGui_send_tm_mcp_mcp_Init return asn1SccGui_send_tm_mcp_mcp;
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide GUI_SUBTYPE;


end GUI_SUBTYPE;