/* Header file for function tc_provider
 * Generated by TASTE on 2023-03-06 19:54:18
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void tc_provider_startup(void);

/* Provided interfaces */
void tc_provider_PI_request_tc( asn1SccMode_Change_Packet * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
