/* Body file for function tm_collection
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "tm_collection_vm_if.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




extern void init_tm_provider(void);
extern unsigned tm_provider_initialized;
unsigned tm_collection_initialized = 0;
void init_tm_collection(void)
{
   if (0 == tm_collection_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      tm_collection_initialized = 1;
      // Call user code startup function
      extern void tm_collection_startup(void);
      tm_collection_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == tm_provider_initialized) {
          init_tm_provider();
      }
      puts ("[TASTE] Initialization completed for function tm_collection");
      tm_collection_initialized = 2;
   }
}
void tm_collection_collect_tm()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tm_collection,collect_tm,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void tm_collection_PI_collect_tm(void);
   tm_collection_PI_collect_tm();
   // puts ("tm_collection_collect_tm called");
}

