/* ASN.1 System configuration file for function tm_collection
 * Generated by TASTE on 2022-12-28 10:47:30
 */

#define __NEED_Temperature_Generic_NATIVE
#define __NEED_Deployment_Digital_NATIVE
#define __NEED_Deployment_Analogue_NATIVE
