/* Body file for function gui
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "gui_vm_if.h"
#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned gui_initialized = 0;
void init_gui(void)
{
   if (0 == gui_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      gui_initialized = 1;
      // Call user code startup function
      extern void gui_startup(void);
      gui_startup();
      puts ("[TASTE] Initialization completed for function gui");
      gui_initialized = 2;
   }
}
void gui_Poll()
{

   //  Directly call user code, no parameters to pass
   extern void gui_PI_Poll(void);
   gui_PI_Poll();
   // puts ("gui_poll called");
}




void gui_send_tm_aoi
      (const char *IN_lfp, size_t IN_lfp_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: gui,send_tm_aoi,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void gui_PI_send_tm_aoi
      (const asn1SccLocation_Fix_Packet *);





   // Call user code
   gui_PI_send_tm_aoi ((asn1SccLocation_Fix_Packet *)IN_lfp);

}




void gui_send_tm_mcp
      (const char *IN_mcp, size_t IN_mcp_len)

{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: gui,send_tm_mcp,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void gui_PI_send_tm_mcp
      (const asn1SccMode_Change_Packet *);





   // Call user code
   gui_PI_send_tm_mcp ((asn1SccMode_Change_Packet *)IN_mcp);

}

