pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");
with OBC_MODEL_DATAVIEW; use OBC_MODEL_DATAVIEW;
pragma Warnings (On, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");



package Context_tm_provider with SPARK_Mode
is


-- asn1SccContext_tm_provider --------------------------------------------

type asn1SccContext_tm_provider is record 
    k : OBC_MODEL_DATAVIEW.asn1SccCounterK;
end record;


function asn1SccContext_tm_provider_Equal(val1, val2 : asn1SccContext_tm_provider) return Boolean;

ERR_CONTEXT_TM_PROVIDER:constant Integer := 181; -- 
ERR_CONTEXT_TM_PROVIDER_K_2:constant Integer := 176; -- 
function asn1SccContext_tm_provider_IsConstraintValid(val : asn1SccContext_tm_provider) return adaasn1rtl.ASN1_RESULT;

function asn1SccContext_tm_provider_Init  return asn1SccContext_tm_provider is
((k => 0));
pragma Warnings (Off, "there are no others");
tm_provider_ctxt : constant Context_tm_provider.asn1SccContext_tm_provider:= asn1SccContext_tm_provider'(
    k => 0 
    ); 
pragma Warnings (On, "there are no others");
private
   --# hide Context_tm_provider;


end Context_tm_provider;