pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



package Payload_subsystem_Datamodel with SPARK_Mode
is


subtype asn1SccPayload_subsystem_States_index_range is Integer range 0..0;
type asn1SccPayload_subsystem_States is (asn1Sccimaging) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccPayload_subsystem_States use
    (asn1Sccimaging => 0);

function asn1SccPayload_subsystem_States_Equal(val1, val2 : asn1SccPayload_subsystem_States) return Boolean;

ERR_PAYLOAD_SUBSYSTEM_STATES:constant Integer := 1; -- imaging
function asn1SccPayload_subsystem_States_IsConstraintValid(val : asn1SccPayload_subsystem_States) return adaasn1rtl.ASN1_RESULT;

function asn1SccPayload_subsystem_States_Init  return asn1SccPayload_subsystem_States is
(asn1Sccimaging);
-- asn1SccPayload_subsystem_Context --------------------------------------------

type asn1SccPayload_subsystem_Context is record 
    state : asn1SccPayload_subsystem_States;
    init_done : adaasn1rtl.Asn1Boolean;
end record;


function asn1SccPayload_subsystem_Context_Equal(val1, val2 : asn1SccPayload_subsystem_Context) return Boolean;

ERR_PAYLOAD_SUBSYSTEM_CONTEXT:constant Integer := 21; -- 
ERR_PAYLOAD_SUBSYSTEM_CONTEXT_STATE_2:constant Integer := 11; -- 
ERR_PAYLOAD_SUBSYSTEM_CONTEXT_INIT_DONE:constant Integer := 16; -- 
function asn1SccPayload_subsystem_Context_IsConstraintValid(val : asn1SccPayload_subsystem_Context) return adaasn1rtl.ASN1_RESULT;

function asn1SccPayload_subsystem_Context_Init  return asn1SccPayload_subsystem_Context is
((state => asn1Sccimaging, init_done => False));
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide Payload_subsystem_Datamodel;


end Payload_subsystem_Datamodel;