pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");
with OBC_MODEL_DATAVIEW; use OBC_MODEL_DATAVIEW;
pragma Warnings (On, "no entities of ""OBC_MODEL_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""OBC_MODEL_DATAVIEW"" has no effect");



package State_handler_entrypoint_Datamodel with SPARK_Mode
is


subtype asn1SccState_handler_entrypoint_States_index_range is Integer range 0..1;
type asn1SccState_handler_entrypoint_States is (asn1Sccwait, asn1Sccsleep) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccState_handler_entrypoint_States use
    (asn1Sccwait => 0, asn1Sccsleep => 1);

function asn1SccState_handler_entrypoint_States_Equal(val1, val2 : asn1SccState_handler_entrypoint_States) return Boolean;

ERR_STATE_HANDLER_ENTRYPOINT_STATES:constant Integer := 1; -- wait | sleep
function asn1SccState_handler_entrypoint_States_IsConstraintValid(val : asn1SccState_handler_entrypoint_States) return adaasn1rtl.ASN1_RESULT;

function asn1SccState_handler_entrypoint_States_Init  return asn1SccState_handler_entrypoint_States is
(asn1Sccwait);
-- asn1SccState_handler_entrypoint_Context --------------------------------------------

type asn1SccState_handler_entrypoint_Context is record 
    state : asn1SccState_handler_entrypoint_States;
    init_done : adaasn1rtl.Asn1Boolean;
    k : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    s : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    w : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    k_max : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    s_max : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    w_max : OBC_MODEL_DATAVIEW.asn1SccCounterK;
    mcp : OBC_MODEL_DATAVIEW.asn1SccMode_Change_Packet;
    lfp : OBC_MODEL_DATAVIEW.asn1SccLocation_Fix_Packet;
end record;


function asn1SccState_handler_entrypoint_Context_Equal(val1, val2 : asn1SccState_handler_entrypoint_Context) return Boolean;

ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT:constant Integer := 156; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_STATE_2:constant Integer := 11; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_INIT_DONE:constant Integer := 16; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_K_2:constant Integer := 26; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_S_2:constant Integer := 36; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_W_2:constant Integer := 46; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_K_MAX_2:constant Integer := 56; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_S_MAX_2:constant Integer := 66; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_W_MAX_2:constant Integer := 76; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_MCP_2:constant Integer := 111; -- 
ERR_STATE_HANDLER_ENTRYPOINT_CONTEXT_LFP_2:constant Integer := 151; -- 
function asn1SccState_handler_entrypoint_Context_IsConstraintValid(val : asn1SccState_handler_entrypoint_Context) return adaasn1rtl.ASN1_RESULT;

function asn1SccState_handler_entrypoint_Context_Init  return asn1SccState_handler_entrypoint_Context is
((state => asn1Sccwait, init_done => False, k => 0, s => 0, w => 0, k_max => 0, s_max => 0, w_max => 0, mcp => OBC_MODEL_DATAVIEW.asn1SccMode_Change_Packet_Init, lfp => OBC_MODEL_DATAVIEW.asn1SccLocation_Fix_Packet_Init));
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide State_handler_entrypoint_Datamodel;


end State_handler_entrypoint_Datamodel;