/* ASN.1 System configuration file for function tm_provider
 * Generated by TASTE on 2023-03-10 20:29:20
 */
#define __NEED_Temperature_Generic_NATIVE
#define __NEED_Deployment_Digital_NATIVE
#define __NEED_Deployment_Analogue_NATIVE

