-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- (Generated by TASTE/Kazoo - $TOOL_SRC/kazoo/templates/glue/language_wrappers/simu_pi_adb/function.tmplt)
with tm_collection;
with loc_provider;
with tc_provider;
with tc_validation;
package body State_Handler_Entrypoint_PI is

   procedure Update_States_For_Synchronous_Calls (Global_State : asn1SccSystem_State) is
   begin
      tm_collection.Ctxt := Global_State.tm_collection;
      loc_provider.Ctxt := Global_State.loc_provider;
      tc_provider.Ctxt := Global_State.tc_provider;
      tc_validation.Ctxt := Global_State.tc_validation;
   end Update_States_For_Synchronous_Calls;

   procedure Update_Global_State_After_Synchronous_Calls (Global_State : in out asn1SccSystem_State)  is
   begin
      Global_State.tm_collection := tm_collection.Ctxt;
      Global_State.loc_provider := loc_provider.Ctxt;
      Global_State.tc_provider := tc_provider.Ctxt;
      Global_State.tc_validation := tc_validation.Ctxt;
   end Update_Global_State_After_Synchronous_Calls;

   procedure Startup (Global_State : in out asn1SccSystem_State) is
   begin
      --  Initialize the global state after startup function has run
      null;
   end Startup;

   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State) is
   begin
     null;
   end Continuous_Signals;

   --  Provided interfaces
   procedure Poll_Aoi (Global_State : in out asn1SccSystem_State) is
   begin
      C_Poll_Aoi;
   end Poll_Aoi;
   
   
   procedure Poll_Mc_Packet (Global_State : in out asn1SccSystem_State) is
   begin
      C_Poll_Mc_Packet;
   end Poll_Mc_Packet;

end State_Handler_Entrypoint_PI;
