// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT
#pragma once
#include "dataview-uniq.h"
#include <assert.h>

typedef enum {
   system_mode_manager_init_timer
} demo_timer_manager_timers;

static struct {
   long long value;
   enum {inactive, active} state;
} timers[1] = {{ .value = 0, .state = inactive }};

void demo_timer_manager_startup(void);
void demo_timer_manager_PI_Tick(void);

void demo_timer_manager_PI_SET_system_mode_manager_init_timer(asn1SccT_UInt32 *val);
void demo_timer_manager_PI_RESET_system_mode_manager_init_timer(void);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
