-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Obc_Model_Dataview; use Obc_Model_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with Simulation_Dataview; use Simulation_Dataview;

package Gui_PI is
   --  Interface to the simulation API
   procedure Startup (Global_State : in out asn1SccSystem_State);
   --  Execute only continuous signals (the simulator shall let the user
   --  send intermediate PIs in the queue since they have priority over
   --  continuous signals)
   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State);

   --  Provided interfaces
   procedure Poll (Global_State : in out asn1SccSystem_State);
   procedure C_Poll
      with Import, Convention => C, Link_Name => "gui_PI_Poll";
   
   
   procedure Send_Tm_Aoi
      (Global_State : in out asn1SccSystem_State;
      Lfp : in out asn1SccLocation_Fix_Packet);
   
   --  Interface to the C implementation of the interface
   procedure C_Send_Tm_Aoi
     (Lfp : in out asn1SccLocation_Fix_Packet)
   
      with Import, Convention => C, Link_Name => "gui_PI_send_tm_aoi";
   
   
   procedure Send_Tm_Mcp
      (Global_State : in out asn1SccSystem_State;
      Mcp : in out asn1SccMode_Change_Packet);
   
   --  Interface to the C implementation of the interface
   procedure C_Send_Tm_Mcp
     (Mcp : in out asn1SccMode_Change_Packet)
   
      with Import, Convention => C, Link_Name => "gui_PI_send_tm_mcp";

end Gui_PI;
