-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-12-02 12:09:45
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with System_Dataview;      use System_Dataview;
package body Gui_RI is

   procedure Trig_Aoi is
      --  Generate an event to the simulator for the output
      Event_Out_State_Handler_Entrypoint : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_State_Handler_Entrypoint.Output_Event :=
        (Source => asn1sccGui,
         Dest   => asn1sccState_Handler_Entrypoint,
         Event  => (Kind => Gui_PRESENT,
                    Gui =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Trig_Aoi_PRESENT,
                        Trig_Aoi => (null record)))));
      Push_Event (Event_Out_State_Handler_Entrypoint);
   
   end Trig_Aoi;
   
   
   
   procedure Trig_Mcp is
      --  Generate an event to the simulator for the output
      Event_Out_State_Handler_Entrypoint : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_State_Handler_Entrypoint.Output_Event :=
        (Source => asn1sccGui,
         Dest   => asn1sccState_Handler_Entrypoint,
         Event  => (Kind => Gui_PRESENT,
                    Gui =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Trig_Mcp_PRESENT,
                        Trig_Mcp => (null record)))));
      Push_Event (Event_Out_State_Handler_Entrypoint);
   
   end Trig_Mcp;
   
   
   
   procedure Trig_Pwr is
      --  Generate an event to the simulator for the output
      Event_Out_State_Handler_Entrypoint : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_State_Handler_Entrypoint.Output_Event :=
        (Source => asn1sccGui,
         Dest   => asn1sccState_Handler_Entrypoint,
         Event  => (Kind => Gui_PRESENT,
                    Gui =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Trig_Pwr_PRESENT,
                        Trig_Pwr => (null record)))));
      Push_Event (Event_Out_State_Handler_Entrypoint);
   
   end Trig_Pwr;

end Gui_RI;
