-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Obc_Model_Dataview; use Obc_Model_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with Simulation_Dataview; use Simulation_Dataview;
with State_Handler_Entrypoint;

package State_Handler_Entrypoint_PI is
   --  Interface to the simulation API
   procedure Startup (Global_State : in out asn1SccSystem_State);
   --  Execute only continuous signals (the simulator shall let the user
   --  send intermediate PIs in the queue since they have priority over
   --  continuous signals)
   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State);

   --  Provided interfaces
   procedure Poll_Aoi (Global_State : in out asn1SccSystem_State);
   
   
   procedure Poll_Mcp (Global_State : in out asn1SccSystem_State);
   
   
   procedure Toggle_Pwr (Global_State : in out asn1SccSystem_State);
   
   
   procedure Trig_Aoi (Global_State : in out asn1SccSystem_State);
   
   
   procedure Trig_Mcp (Global_State : in out asn1SccSystem_State);
   
   
   procedure Trig_Pwr (Global_State : in out asn1SccSystem_State);

end State_Handler_Entrypoint_PI;
