-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-12-02 12:09:45
with Simulator;            use Simulator;
with Simulation_Dataview;  use Simulation_Dataview;
with System_Dataview;      use System_Dataview;
with tm_collection;
with loc_provider;
with tc_provider;
with tc_validation;
package body State_Handler_Entrypoint_RI is

   procedure Collect_Tm is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Tm_Collection.Collect_Tm;
   end Collect_Tm;
   
   
   
   procedure Request_Loc
      (Lfp : out asn1SccLocation_Fix_Packet) is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Loc_Provider.Request_Loc (lfp);
   end Request_Loc;
   
   
   
   procedure Request_Tc
      (Mcp : out asn1SccMode_Change_Packet) is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Tc_Provider.Request_Tc (mcp);
   end Request_Tc;
   
   
   
   procedure Send_Tm_Aoi
      (Lfp : in out asn1SccLocation_Fix_Packet) is
      --  Generate an event to the simulator for the output
      Event_Out_Gui : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Gui.Output_Event :=
        (Source => asn1sccState_Handler_Entrypoint,
         Dest   => asn1sccGui,
         Event  => (Kind => State_Handler_Entrypoint_PRESENT,
                    State_Handler_Entrypoint =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Send_Tm_Aoi_PRESENT,
                     Send_Tm_Aoi =>
                           (Lfp => Lfp)))));
      Push_Event (Event_Out_Gui);
   
   end Send_Tm_Aoi;
   
   
   
   procedure Send_Tm_Mcp
      (Mcp : in out asn1SccMode_Change_Packet) is
      --  Generate an event to the simulator for the output
      Event_Out_Gui : asn1SccObservable_Event (Kind => Output_Event_PRESENT);
   begin
      Event_Out_Gui.Output_Event :=
        (Source => asn1sccState_Handler_Entrypoint,
         Dest   => asn1sccGui,
         Event  => (Kind => State_Handler_Entrypoint_PRESENT,
                    State_Handler_Entrypoint =>
                      (Kind   => Msg_Out_PRESENT,
                       Msg_Out =>
                          (Kind => Send_Tm_Mcp_PRESENT,
                     Send_Tm_Mcp =>
                           (Mcp => Mcp)))));
      Push_Event (Event_Out_Gui);
   
   end Send_Tm_Mcp;
   
   
   
   procedure Validate_Mc_Vs_Tm is
   begin
      --  The global state of the callee has been set, so we can make a direct call
      Tc_Validation.Validate_Mc_Vs_Tm;
   end Validate_Mc_Vs_Tm;

end State_Handler_Entrypoint_RI;
