// Body file for function blinker
// Generated by TASTE on 2023-03-11 00:04:36
// You can edit this file, it will not be overwritten
// Provided interfaces : blink_trigger
// Required interfaces : toggle_led
// User-defined properties for this function:
//   |_ Taste::Startup_Priority = 1
// Timers              : 

#include "blinker.h"
#include "blinker_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
blinker_state ctxt_blinker;


void blinker_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // std::cout << "[blinker] Startup" << std::endl;
}

void blinker_PI_blink_trigger(void)
{
   // Write your code here
    blinker_RI_toggle_led();
}


