/* Header file for function blinker
 * Generated by TASTE on 2023-03-11 00:05:02
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void blinker_startup(void);

/* Provided interfaces */
void blinker_PI_blink_trigger( );

/* Required interfaces */
extern void blinker_RI_toggle_led( );


#ifdef __cplusplus
}
#endif

