--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body State_Handler_Entrypoint_RI is
   procedure collect_tm is null;
   procedure request_loc (Lfp : out asn1SccLocation_Fix_Packet) is null;
   procedure request_tc (Mcp : out asn1SccMode_Change_Packet) is null;
   procedure validate_mc_vs_tm is null;
end State_Handler_Entrypoint_RI;