--  This file was generated by TASTE: DO NOT EDIT

with OBC_MODEL_DATAVIEW; use OBC_MODEL_DATAVIEW; pragma Unreferenced (OBC_MODEL_DATAVIEW);
with TASTE_BasicTypes; use TASTE_BasicTypes; pragma Unreferenced (TASTE_BasicTypes);
with System_Dataview; use System_Dataview; pragma Unreferenced (System_Dataview);
with GUI_SUBTYPE; use GUI_SUBTYPE; pragma Unreferenced (GUI_SUBTYPE);

package ASN1_Ada_Iterators is
end ASN1_Ada_Iterators;