/* Body file for function state_handler_entrypoint
 * Generated by TASTE on 2022-12-28 10:33:12
 */
#include "state_handler_entrypoint_vm_if.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




extern void init_tm_collection(void);
extern unsigned tm_collection_initialized;
extern void init_loc_provider(void);
extern unsigned loc_provider_initialized;
extern void init_tc_provider(void);
extern unsigned tc_provider_initialized;
extern void init_tc_validation(void);
extern unsigned tc_validation_initialized;
unsigned state_handler_entrypoint_initialized = 0;
void init_state_handler_entrypoint(void)
{
   if (0 == state_handler_entrypoint_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      state_handler_entrypoint_initialized = 1;
      // Call user code startup function
      extern void state_handler_entrypoint_startup(void);
      state_handler_entrypoint_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == tm_collection_initialized) {
          init_tm_collection();
      }
      if (0 == loc_provider_initialized) {
          init_loc_provider();
      }
      if (0 == tc_provider_initialized) {
          init_tc_provider();
      }
      if (0 == tc_validation_initialized) {
          init_tc_validation();
      }
      puts ("[TASTE] Initialization completed for function state_handler_entrypoint");
      state_handler_entrypoint_initialized = 2;
   }
}
void state_handler_entrypoint_poll_aoi()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,poll_aoi,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_poll_aoi(void);
   state_handler_entrypoint_PI_poll_aoi();
   // puts ("state_handler_entrypoint_poll_aoi called");
}




void state_handler_entrypoint_poll_mcp()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,poll_mcp,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_poll_mcp(void);
   state_handler_entrypoint_PI_poll_mcp();
   // puts ("state_handler_entrypoint_poll_mcp called");
}




void state_handler_entrypoint_toggle_pwr()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,toggle_pwr,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_toggle_pwr(void);
   state_handler_entrypoint_PI_toggle_pwr();
   // puts ("state_handler_entrypoint_toggle_pwr called");
}




void state_handler_entrypoint_trig_aoi()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,trig_aoi,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_aoi(void);
   state_handler_entrypoint_PI_trig_aoi();
   // puts ("state_handler_entrypoint_trig_aoi called");
}




void state_handler_entrypoint_trig_mcp()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,trig_mcp,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_mcp(void);
   state_handler_entrypoint_PI_trig_mcp();
   // puts ("state_handler_entrypoint_trig_mcp called");
}




void state_handler_entrypoint_trig_pwr()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: state_handler_entrypoint,trig_pwr,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void state_handler_entrypoint_PI_trig_pwr(void);
   state_handler_entrypoint_PI_trig_pwr();
   // puts ("state_handler_entrypoint_trig_pwr called");
}

