/* Header file for function tm_provider
 * Generated by TASTE on 2023-03-10 20:29:19
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void tm_provider_startup(void);

/* Provided interfaces */
void tm_provider_PI_request_tm( asn1SccTemperature_Generic *, asn1SccDeployment_Digital *, asn1SccDeployment_Analogue * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
