/* Body file for function tm_provider
 * Generated by TASTE on 2022-11-27 16:30:03
 * You can edit this file, it will not be overwritten
 * Provided interfaces : request_tm
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "tm_provider.h"
//#include <stdio.h>


void tm_provider_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[tm_provider] Startup");
}

void tm_provider_PI_request_tm
      (asn1SccTemperature_Generic *OUT_temp,
       asn1SccDeployment_Digital *OUT_depl_d,
       asn1SccDeployment_Analogue *OUT_depl_a)

{
   // Write your code here
}


