/* Header file for function tc_validation
 * Generated by TASTE on 2023-03-06 19:54:18
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void tc_validation_startup(void);

/* Provided interfaces */
void tc_validation_PI_validate_mc_vs_tm( );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

