// Body file for function tc_validation
// Generated by TASTE on 2022-11-27 16:30:03
// You can edit this file, it will not be overwritten
// Provided interfaces : validate_mc_vs_tm
// Required interfaces : 
// User-defined properties for this function:
//   |_ Taste::Startup_Priority = 1
// Timers              : 

#include "tc_validation.h"
#include "tc_validation_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
tc_validation_state ctxt_tc_validation;


void tc_validation_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // std::cout << "[tc_validation] Startup" << std::endl;
}

void tc_validation_PI_validate_mc_vs_tm(void)
{
   // Write your code here
}


