/* Header file for function led_blinker
 * Generated by TASTE on 2023-03-10 23:38:53
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void led_blinker_startup(void);

/* Provided interfaces */
void led_blinker_PI_trigger_blink( void );

/* Required interfaces */
extern void led_blinker_RI_led_blink( void );


#ifdef __cplusplus
}
#endif
