/* Body file for function led_blinker
 * Generated by TASTE on 2023-03-10 23:38:30
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger_blink
 * Required interfaces : led_blink
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "led_blinker.h"
//#include <stdio.h>


void led_blinker_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[led_blinker] Startup");
}

void led_blinker_PI_trigger_blink(void)
{
   // Write your code here
    led_blinker_RI_led_blink();
}


