--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2022-12-28 10:47:30
with Obc_Model_Dataview; use Obc_Model_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with adaasn1rtl;
with Interfaces.C.Strings; use Interfaces.C.Strings;

package State_Handler_Entrypoint_RI is

   procedure Collect_Tm;
   
   
   procedure Request_Loc (Lfp : out asn1SccLocation_Fix_Packet);
   
   
   procedure Request_Tc (Mcp : out asn1SccMode_Change_Packet);
   
   
   procedure Send_Tm_Aoi (Lfp : in out asn1SccLocation_Fix_Packet);
   
   
   procedure Send_Tm_Mcp (Mcp : in out asn1SccMode_Change_Packet);
   
   
   procedure Validate_Mc_Vs_Tm;

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "state_handler_entrypoint_check_queue";

   --  Return the SDL state as a char * for the MSC tracing function
   function To_C_Pointer (State_As_String : String) return Chars_Ptr is
      (New_String (State_As_String));
end State_Handler_Entrypoint_RI;
