/* Body file for function tm_collection
 * Generated by TASTE on 2023-03-06 19:54:19
 */
#include "tm_collection_vm_if.h"




extern void init_tm_provider(void);
extern unsigned tm_provider_initialized;
unsigned tm_collection_initialized = 0;
void init_tm_collection(void)
{
   if (0 == tm_collection_initialized) {
      tm_collection_initialized = 1;
      // Call user code startup function
      extern void tm_collection_startup(void);
      tm_collection_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == tm_provider_initialized) {
          init_tm_provider();
      }
      tm_collection_initialized = 2;
   }
}
void tm_collection_collect_tm()
{

   //  Directly call user code, no parameters to pass
   extern void tm_collection_PI_collect_tm(void);
   tm_collection_PI_collect_tm();
   // puts ("tm_collection_collect_tm called");
}

