/* Body file for function tm_collection
 * Generated by TASTE on 2023-03-17 00:46:27
 */
#include "tm_collection_vm_if.h"




unsigned tm_collection_initialized = 0;
void init_tm_collection(void)
{
   if (0 == tm_collection_initialized) {
      tm_collection_initialized = 1;
      // Call user code startup function
      extern void tm_collection_startup(void);
      tm_collection_startup();
      tm_collection_initialized = 2;
   }
}
void tm_collection_collect_tm()
{

   //  Directly call user code, no parameters to pass
   extern void tm_collection_PI_collect_tm(void);
   tm_collection_PI_collect_tm();
   // puts ("tm_collection_collect_tm called");
}

