/* Header file for function print_service
 * Generated by TASTE on 2023-03-20 00:41:13
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void print_service_startup(void);

/* Provided interfaces */
void print_service_PI_print( const asn1SccOString * );


void print_service_PI_wait( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
