/* Header file for function loc_provider
 * Generated by TASTE on 2022-12-28 10:47:29
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void loc_provider_startup(void);

/* Provided interfaces */
void loc_provider_PI_request_loc( asn1SccLocation_Fix_Packet * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
