/* Header file for function HAL
 * Generated by TASTE on 2023-02-18 14:39:03
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void hal_startup(void);

/* Provided interfaces */
void hal_PI_get_current_temperature( asn1SccTEMPERATURE * );


void hal_PI_get_current_voltage( asn1SccVOLTAGE * );


void hal_PI_oled_load_register( const asn1SccUINT8T *, asn1SccT_Boolean * );


void hal_PI_oled_set_data_enable( const asn1SccT_Boolean *, asn1SccT_Boolean * );


void hal_PI_oled_turn_on_off( const asn1SccT_Boolean *, asn1SccT_Boolean * );


void hal_PI_set_pwm( const asn1SccDUTY_CYCLE * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
