/* Body file for function tc_validation
 * Generated by TASTE on 2022-12-28 10:47:30
 */
#include "tc_validation_vm_if.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);




unsigned tc_validation_initialized = 0;
void init_tc_validation(void)
{
   if (0 == tc_validation_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      tc_validation_initialized = 1;
      // Call user code startup function
      extern void tc_validation_startup(void);
      tc_validation_startup();
      puts ("[TASTE] Initialization completed for function tc_validation");
      tc_validation_initialized = 2;
   }
}
void tc_validation_validate_mc_vs_tm()
{
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tc_validation,validate_mc_vs_tm,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void tc_validation_PI_validate_mc_vs_tm(void);
   tc_validation_PI_validate_mc_vs_tm();
   // puts ("tc_validation_validate_mc_vs_tm called");
}

