/* Header file for function tm_provider
 * Generated by TASTE on 2022-12-28 10:47:30
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void tm_provider_startup(void);

/* Provided interfaces */
void tm_provider_PI_request_tm( asn1SccTemperature_Generic *, asn1SccDeployment_Digital *, asn1SccDeployment_Analogue * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
