-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Obc_Model_Dataview; use Obc_Model_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with Simulation_Dataview; use Simulation_Dataview;

package Loc_Provider_PI is
   --  Interface to the simulation API
   procedure Startup (Global_State : in out asn1SccSystem_State);
   --  Execute only continuous signals (the simulator shall let the user
   --  send intermediate PIs in the queue since they have priority over
   --  continuous signals)
   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State);

   --  Provided interfaces
   procedure Request_Loc
      (Global_State : in out asn1SccSystem_State;
      Lfp :    out asn1SccLocation_Fix_Packet);
   
   --  Interface to the C implementation of the interface
   procedure C_Request_Loc
     (Lfp :    out asn1SccLocation_Fix_Packet)
   
      with Import, Convention => C, Link_Name => "loc_provider_PI_request_loc";

end Loc_Provider_PI;
