#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1CounterK(const char *paramName, const asn1SccCounterK *pData);
void PrintASN1Time_UNIX(const char *paramName, const asn1SccTime_UNIX *pData);
void PrintASN1Latitude_WGS84(const char *paramName, const asn1SccLatitude_WGS84 *pData);
void PrintASN1Longitude_WGS84(const char *paramName, const asn1SccLongitude_WGS84 *pData);
void PrintASN1Location(const char *paramName, const asn1SccLocation *pData);
void PrintASN1Location_Fix_Packet(const char *paramName, const asn1SccLocation_Fix_Packet *pData);
void PrintASN1Temperature_Generic(const char *paramName, const asn1SccTemperature_Generic *pData);
void PrintASN1Deployment_Digital(const char *paramName, const asn1SccDeployment_Digital *pData);
void PrintASN1Deployment_Analogue(const char *paramName, const asn1SccDeployment_Analogue *pData);
void PrintASN1System_Mode(const char *paramName, const asn1SccSystem_Mode *pData);
void PrintASN1Subsystem_Address(const char *paramName, const asn1SccSubsystem_Address *pData);
void PrintASN1Mode_Change_Packet(const char *paramName, const asn1SccMode_Change_Packet *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);
void PrintASN1PID(const char *paramName, const asn1SccPID *pData);

#ifdef __cplusplus
}
#endif

#endif
